function XinRanAnalysis2_Sweep(varargin)
% Xintrinsic continuous sweep based session analysis
%   S.TrlNumTotal is supposed to be 1
%   Stimulation is supposed to vary a feature continuously in a cycle
% clearvars;
clear global
global A T
%% Get preprocessed ('*_P?.mat') file
if nargin ==0
    % Calling from direct running of the function
    A.RunningSource =   'D';
    [A.FileName, A.PathName, A.FilterIndex] = uigetfile(...
                        'W:\*_P?.mat',...
                        'Select a "_P1.mat" file to process');
    if A.FilterIndex == 0
        clear A;
        return
    end
    if iscell(A.FileName) == 0  % single file selected
        A.FileName =    {A.FileName};
    end
else
    A.RunningSource =   'S';
    % Calling from another script
    [A.PathName, A.FileName, FileExt] = fileparts(varargin{1});
    A.PathName =        [A.PathName, '\'];
    A.FileName =        {[A.FileName, FileExt]};
end
%% Load data files
global P S
A.FullFileName =    [A.PathName, A.FileName{1}];   
A.FileNameSplits =	strsplit(A.FileName{1}, '_');
A.FileNameS =       strjoin(A.FileNameSplits(1:5), '_');
load([A.PathName A.FileNameS '.mat'], 'S');	% load S (Saved from recording)
load([A.FullFileName(1:end-4) '.mat'], 'P');	% load P (Preprocessed)  
A.SoundFileName =   S.SesSoundFile;
A.SoundWave =       S.SesSoundWave;
if A.RunningSource == 'D'
    if S.TrlNumTotal == 1
        disp([  'Analyzing session: "', A.FileName{1}, ...
                '" with the sound: "', A.SoundFileName, '"']);
    else
        disp([  'Session: "', A.FileName{1}, ...
                '" with the sound: "', A.SoundFileName, '" is not a Sweep based session.']);
        return
    end
end
switch [A.FileNameSplits{2}(1:3) '_' A.FileNameSplits{4}(1:4) '_'  A.FileNameSplits{5}(1:3)]
    case 'NIR_Ring_PBS';    A.Polarity =    -1;     A.PseudoDelay =	2.6;
    case 'NIR_Pola_PBS';    A.Polarity =    -1;     A.PseudoDelay =	2.6;
    case 'Far_Pola_PBS';    A.Polarity =     1;     A.PseudoDelay =	2.6;
    case 'FRe_Pola_PBS';    A.Polarity =     1;     A.PseudoDelay =	2.6;
    case 'Red_Pola_PBS';    A.Polarity =     1;     A.PseudoDelay =	2.6;
    case 'Yel_Pola_PBS';    A.Polarity =     1;     A.PseudoDelay =	2.6;
    case 'Amb_Pola_PBS';    A.Polarity =     1;     A.PseudoDelay =	2.6;
    case 'Gre_Pola_PBS';    A.Polarity =    -1;     A.PseudoDelay =	2.6;
    case 'Blu_Pola_PBS';    A.Polarity =    -1;     A.PseudoDelay =	2.6;
    case 'Blu_Fluo_GFP';    A.Polarity =     1;     A.PseudoDelay = 0.0;
    otherwise;              A.Polarity =     1;     A.PseudoDelay =	2.6;
end
A.PseudoDelay =	3.7;
A.DispPixelWidth0 =     120;
A.DispPixelHeight0 =	75;

%% Figure 1: ROI
T.S.FS1 =        [100 75];	% Space, Figure Side
    T.H.hFig1 = figure(...
                    'Name',         ['Determine the ROI in the session "', A.FileName{1}(1:end-7), '"'],...
                    'Units',        'pixels',...  
                    'Position',     [   10,                     10,...
                                        T.S.FS1(1)*2+A.DispPixelWidth0*5,...
                                        T.S.FS1(2)*2+A.DispPixelHeight0*5 ]);
    T.H.hFig1Axes1 = axes(...
                    'Parent',       T.H.hFig1,...
                    'Units',        'pixels',...  
                    'Position',     [   T.S.FS1(1),             T.S.FS1(2),...
                                        A.DispPixelWidth0*5,	A.DispPixelHeight0*5 ]);
	T.H.hFig1Axes1Image1 = imagesc(	squeeze(P.ProcDataMat(1,1,:,:,1)) + ...             
                                    squeeze(P.ProcDataMat(end,end,:,:,end)),...
                    'Parent',       T.H.hFig1Axes1);    
	colormap(T.H.hFig1Axes1,        'gray');
    title(                       	'Drag to position the ROI, double click on the circle to finish');
    try 
        if strcmp(S.MkyPrep, 'Skull')
            T.H.hFig1Axes1ROI = imellipse(gca, [	0 	0   ...
                                                    P.ProcPixelWidth+1 P.ProcPixelHeight+1]);
        else
            T.H.hFig1Axes1ROI = imellipse(gca, [	ceil(0.5*(P.ProcPixelWidth-P.ProcPixelHeight))	0	...
                                                    P.ProcPixelHeight+1	P.ProcPixelHeight+1]);
        end
    catch
            T.H.hFig1Axes1ROI = imellipse(gca, [	ceil(0.5*(P.ProcPixelWidth-P.ProcPixelHeight))	0	...
                                                    P.ProcPixelHeight+1	P.ProcPixelHeight+1]);            
    end 
    if A.RunningSource == 'D'
        wait(T.H.hFig1Axes1ROI);
    end
    title(                          'Done, start calculating...');
    drawnow;
%% Setup Parmateters: Data & Numbers 
A.N_BinSat =        2^12*4^2 *P.ProcPixelBinNum^2 *P.ProcFrameBinNum;          
A.N_Ph =            P.ProcPixelHeight;      % Number_PixelHeight
A.N_Pw =            P.ProcPixelWidth;       % Number_PixelWidth
A.N_Pt =            A.N_Ph * A.N_Pw;        % Number_PixelTotal(in each frame in the P?.mat)
A.N_PhSelect =      37;
A.N_PwSelect =      60;

try
    if S.SysCamFrameRate ~=80
        A.N_Tpf =	P.ProcFrameBinNum/S.SysCamFrameRate;	
    else
        A.N_Tpf =	P.ProcFrameBinNum/80;
    end
catch
        A.N_Tpf =	P.ProcFrameBinNum/80;   % Number_TimePerFrame
end
A.N_Ttps =          S.TrlDurPreStim;        % Number_TimeTrialPreStim
A.N_Tts =           S.TrlDurStim;           % Number_TimeTrialStim
A.N_Ttt =           S.TrlDurTotal;          % Number_TimeTrialTotal
A.N_Tst =           S.SesDurTotal;          % NUmber_TimeSessionTotal
A.N_Ct =            S.SesCycleNumTotal;	% Number_CycleTotal (in the session)
A.FileNameMod =     '';
% % % % % % Manually switch session temporal arrangement if here.
%     A.N_Ct =  19;       
%         A.N_Ttt =   A.N_Tst/A.N_Ct;
%         A.N_Tts =   A.N_Ttt - A.N_Ttps;
%         A.FileNameMod = sprintf('_%drep', A.N_Ct);
% % % % % % Manually switch session temporal arrangement if here.

A.N_Fps =           1/A.N_Tpf;              % Number_FramePerSecond
A.N_Ft =            P.ProcFrameNumTotal;    % Number_FrameTotal
A.N_Fpt =           A.N_Ft / A.N_Ct;        % Number_FramePerTrial
A.N_Ftpreoff =      round(  A.N_Ttps *          P.ProcFrameRate); 
                                            % Number_FrameTrialPrestimOff
A.N_Ftstimoff =     round(( A.N_Ttps+A.N_Tts) * P.ProcFrameRate);
                                            % Number_FrameTrialStimOff
% Region of Interest
A.PhPw_ROIin =          createMask(T.H.hFig1Axes1ROI);          % ROI in
A.Pt_ROIin =            reshape(A.PhPw_ROIin,     A.N_Pt, []);  % ROI in 
A.Pt_ROIout =           reshape(~A.PhPw_ROIin,    A.N_Pt, []);  % ROI out
A.PtIndex_ROIin =       single(find(A.Pt_ROIin));

% Spectral & Temporal Analysis
A.N_Qt =                A.N_Ft;         % Number_FrequencyTotal
A.N_Qfc =               A.N_Ct +1;      % Number_FrequencyOfTheCycle  
A.Qt_Freqs =            single(0:  1/(A.N_Ft/A.N_Fps): (A.N_Ft-1)/(A.N_Ft/A.N_Fps));
A.OnePt_ProcPower =     P.ProcMeanPower;
A.FptCtPhPw_DataRaw =   reshape( permute(P.ProcDataMat, [5 2 1 3 4]),...
                                A.N_Fpt, A.N_Ct, A.N_Ph, A.N_Pw );
A.FtPt_DataRaw =        reshape(A.FptCtPhPw_DataRaw,	A.N_Ft,	A.N_Pt);  
A.PhPw_ImageMeanRaw =   squeeze(mean(mean(A.FptCtPhPw_DataRaw, 1), 2));
A.OnePt_ImageMeanRaw =	reshape(A.PhPw_ImageMeanRaw, 1, A.N_Pt);
    % No more data from "S" & "P" is needed below 

%% Variance Analysis 
T.dAxesVarIntScaleLim =     [0 1];
T.dAxesVarStdScaleLim =     [0.0001,  0.1];
T.dAxesVarStdScaleLimLog =  log10(T.dAxesVarStdScaleLim);
T.dAxesVarStdScaleTickLog =	T.dAxesVarStdScaleLimLog(1):1:T.dAxesVarStdScaleLimLog(2);
T.dAxesVarStdScaleTickLabels =	cellfun(@(x) sprintf('%5.2f%%', x),...
                            num2cell(100*10.^T.dAxesVarStdScaleTickLog),...
                            'UniformOutput',    false); 
i=1;
A.Fig2Var{i}.Title =        'Average intensity (% to saturation)';
A.Fig2Var{i}.ColorMap =     'gray';  
A.Fig2Var{i}.PhPw_Data =	single(squeeze(mean(mean(A.FptCtPhPw_DataRaw, 1),  2)) / A.N_BinSat);
i=2;
A.Fig2Var{i}.Title =        'STD across cycles (mean across frames)';
A.Fig2Var{i}.ColorMap =     'parula';
A.Fig2Var{i}.PhPw_Data =	single( squeeze(std(mean(A.FptCtPhPw_DataRaw, 1), 0, 2))    ./A.PhPw_ImageMeanRaw );
i=3;
A.Fig2Var{i}.Title =        'STD across frames (mean across cycles)';
A.Fig2Var{i}.ColorMap =     'parula'; 
A.Fig2Var{i}.PhPw_Data =	single( squeeze(std(mean(A.FptCtPhPw_DataRaw, 2), 0, 1))    ./A.PhPw_ImageMeanRaw );
% i=4;
% A.Fig2Var{i}.Title =        'STD, entire session';
% A.Fig2Var{i}.ColorMap =     'parula';
% A.Fig2Var{i}.PhPw_Data =	reshape(std(A.FtPt_DataRaw, 0, 1), A.N_Ph, A.N_Pw)  ./A.PhPw_ImageMeanRaw;
%% Spectral Analysis  
% Power meter
A.OneQt_PowerFFTRaw =   fft(A.OnePt_ProcPower);
A.OneQt_PowerFFTAmp =   abs(A.OneQt_PowerFFTRaw)*sqrt(2)/A.N_Qt / A.OneQt_PowerFFTRaw(1);
% Camera: normalized
A.FtPt_NormSes =	A.FtPt_DataRaw./(ones(A.N_Ft, 1)*A.OnePt_ImageMeanRaw) - 1;
A.PtQt_FFTRaw =     fft(A.Polarity * A.FtPt_NormSes)';     
A.PtQt_FFTAmp =     single(abs( A.PtQt_FFTRaw)*sqrt(2)/A.N_Qt);	
                                % Amp: mirror combined, thus sqrt(2)
A.PtQt_FFTAgl =     mod(angle(	A.PtQt_FFTRaw)- ...
                        A.PseudoDelay*ones(A.N_Pt,1)*A.Qt_Freqs*2*pi, 2*pi);
                                % Agl: phase in [0, 2*pi], with
                                % pseudo-delay compensated
if contains(lower(A.SoundFileName), 'down')
    A.PtQt_FFTAgl =	2*pi - A.PtQt_FFTAgl;
end                             % Reverse the angle for DOWN cycle 
% collapse across pixels
A.OneQt_FFTAmpMeanOut =	sum(A.PtQt_FFTAmp.*(A.Pt_ROIout *ones(1,A.N_Qt)))/  sum(A.Pt_ROIout);
A.OneQt_FFTAmpMeanIn =	sum(A.PtQt_FFTAmp.*(A.Pt_ROIin  *ones(1,A.N_Qt)))/  sum(A.Pt_ROIin);
A.OneQt_FFTAmpMeanPStdIn =	A.OneQt_FFTAmpMeanIn + std(A.PtQt_FFTAmp(A.PtIndex_ROIin,:),1);
    % the locking frequency, Prepare the raw hue, sat, val
        % A.N_Ttps =   2.5;
        % A.N_Tts =      15;
    A.PtOne_Hue =	A.PtQt_FFTAgl(:,A.N_Qfc)/(2*pi);
    A.PtOne_Hue =	(A.PtOne_Hue-A.N_Ttps/A.N_Ttt) /...
                        (A.N_Tts/A.N_Ttt);   % match the Stimulus ONSET / OFFSET to 0-1
    A.PtOne_Sat =	single(ones(A.N_Pt,1));          
    A.PtOne_Val =	A.PtQt_FFTAmp(:,A.N_Qfc); 
A.PhPwThree_TuneMap =   uint8(zeros(A.N_Ph, A.N_Pw,3));
% Spectrum scale
T.dAxesSpecXTick =      [A.Qt_Freqs(A.N_Ct+1),  mean(A.Qt_Freqs([2, end]))]; 
T.dAxesSpecYTick =      [0 0.000125*2.^(0:8)];
T.dAxesSpecYTickLabel =	cellfun(@(x) sprintf('%5.3f%%', x),...
                            num2cell(round(100000*T.dAxesSpecYTick)/1000),...
                            'UniformOutput',    false); 
T.dAxesSpecDotX =       A.Qt_Freqs(A.N_Ct+1);
T.dAxesSpecDotY =       T.dAxesSpecYTick( find(T.dAxesSpecYTick>max( [...
                            A.OneQt_FFTAmpMeanOut(      A.N_Ct+1),...
                            A.OneQt_FFTAmpMeanIn(       A.N_Ct+1),...    
                            A.OneQt_FFTAmpMeanPStdIn(   A.N_Ct+1)]),1));                   
%% Trial Analysis
A.FptCtPhPw_NormSes =	single(reshape(A.FtPt_NormSes, A.N_Fpt, A.N_Ct, A.N_Ph, A.N_Pw));
% Pixel nomalized in the session by the mean of prestim/all frames 
if A.N_Ftpreoff >0
    A.OneCtPhPw_PreMean = mean( A.FptCtPhPw_NormSes(1:A.N_Ftpreoff, :, :, :), 1);   % with pre-stim time as baseline
else
    A.OneCtPhPw_PreMean = mean( A.FptCtPhPw_NormSes(1:end,          :, :, :), 1);	% continuous, so total average us baseline
end
A.FptCtPhPw_NormTrl =   (A.FptCtPhPw_NormSes+1)./(repmat(A.OneCtPhPw_PreMean, A.N_Fpt,1,1,1)+1) -1;	% for Axes: Pixl           
A.FptPhPw_NormTrl =     squeeze(mean(A.FptCtPhPw_NormTrl, 2));
A.FptPt_NormTrl =       reshape(A.FptPhPw_NormTrl, A.N_Fpt, A.N_Pt);                                % for Axes: Temp
A.PtIn_STD =            squeeze(std(A.FptPt_NormTrl(:,A.PtIndex_ROIin), 1));
A.PtIn_STD_max =        max(A.PtIn_STD);
A.PtIn_STD_mean =       mean(A.PtIn_STD);
A.FptPhPw_NormTrlAdj =  A.FptPhPw_NormTrl*A.Polarity;                                               % for Axes: Frme
T.dAxesTempYLims =      [   0.005   0.01    0.02    0.05    0.1     0.2     0.5];
T.dAxesTempYLimInd =	find(T.dAxesTempYLims>A.PtIn_STD_max, 1);
if T.dAxesTempYLimInd == 1; T.dAxesTempYLimInd = length(T.dAxesTempYLims);
else;                       T.dAxesTempYLimInd = T.dAxesTempYLimInd -1;
end
T.dAxesTempYLim =           T.dAxesTempYLims(T.dAxesTempYLimInd);
%% Graphics
% Figure
T.S.FS2 =       [   75      120;...
                    105     30];
T.VarMag =	3.0;        T.N_PwVar = A.DispPixelWidth0*T.VarMag;    T.N_PhVar = A.DispPixelHeight0*T.VarMag;              
T.ImgMag =	3.0;        T.N_PwImg = A.DispPixelWidth0*T.ImgMag;    T.N_PhImg = A.DispPixelHeight0*T.ImgMag; 
T.S.BA =        [90 90];    % Space, Between Axes
T.S.CBW =       10;         % Space, ColorBarWidth
T.S.CBTW =      20;         % Space, ColorBarTextWidth
T.FontSizeS =   8;
delete(T.H.hFig1);
T.H.hFig2 = figure(...
                'Name',         ['"', A.FileName{1}, '" with the sound: "', A.SoundFileName, '"'],...
                'Units',        'pixels',...  
                'Position',     [   10,                     10, ...
                                    sum(T.S.FS2(1,:))+(T.S.BA(1)*1)*2+T.N_PwVar*3, ...
                                    sum(T.S.FS2(2,:))+(T.S.BA(2)*1)*2+T.N_PhVar*1+T.N_PhImg*2],...
                'Color',        [1 1 1]);
addToolbarExplorationButtons(gcf);
T.H.hFig2Text1 = uicontrol(...
                'Style',        'text',...
                'Parent',       T.H.hFig2,...
                'Position',     [0 0 200 30],...
                'BackgroundColor', [1 1 1],...
                'String',       'Xintrinsic @ phase-encoded experiment design, anaylsis code by Xindong Song',...
                'Enable',       'off',...
                'Tag',          'TitlTex1');
%                 'ButtonDownFcn',@XinRanAnalysis2_Sweep_ButtonDown       
T.H.hFig2Text2 = uicontrol(...
                'Style',        'text',...
                'Parent',       T.H.hFig2,...
                'Position',     [250 0 200 30],...
                'BackgroundColor', [1 1 1],...
                'String',       'Click here to have the current figure captured to the windows clipboard',...
                'Enable',       'off',...
                'Tag',          'TitlTex2',...
                'ButtonDownFcn',@XinRanAnalysis2_Sweep_ButtonDown);    
T.H.hFig2Text3 = uicontrol(...
                'Style',        'text',...
                'Parent',       T.H.hFig2,...
                'Position',     [500 0 200 30],...
                'BackgroundColor', [1 1 1],...
                'String',       'Click here to have the SESSION NAME copied to the windows clipboard',...
                'Enable',       'off',...
                'Tag',          'TitlTex3',...
                'ButtonDownFcn',@XinRanAnalysis2_Sweep_ButtonDown);   
T.H.hFig2Text4 = uicontrol(...
                'Style',        'text',...
                'Parent',       T.H.hFig2,...
                'Position',     [750 0 200 30],...
                'BackgroundColor', [1 1 1],...
                'String',       'Click here to have the SOUND NAME copied to the windows clipboard',...
                'Enable',       'off',...
                'Tag',          'TitlTex4',...
                'ButtonDownFcn',@XinRanAnalysis2_Sweep_ButtonDown);      
%% Axes: Variance        
for i = 1:length(A.Fig2Var)
    T.H.hFig2AxesVar(i) = axes(...
                'Parent',       T.H.hFig2,...
                'Units',        'pixels',...  
                'Position',     [   T.S.FS2(1,1)+  (T.S.BA(1)*1)*(i-1	)+  T.N_PwVar*(i-1	), ...
                                    T.S.FS2(2,1), ...
                                    T.N_PwVar,  T.N_PhVar],...
                'Tag',          [num2str(i), 'Var'],...
                'Toolbar',      [],...
                'LabelFontSizeMultiplier', 1);
    if strcmp(A.Fig2Var{i}.Title(1:3), 'STD')
        imagesc(    log10(      A.Fig2Var{i}.PhPw_Data)    );
        caxis(                  T.dAxesVarStdScaleLimLog);
    else
        imagesc(                A.Fig2Var{i}.PhPw_Data     );
        caxis(                  T.dAxesVarIntScaleLim);
    end
    set(gca,    'XTick',        []);
    set(gca,    'YTick',        []);
    colormap(   T.H.hFig2AxesVar(i), A.Fig2Var{i}.ColorMap);
    T.H.hFig2AxesVarColorbar(i) = colorbar(...
                'peer',         T.H.hFig2AxesVar(i),...
                'Units',        'pixels',...
                'Position',     [   T.S.FS2(1,1)+  (T.S.BA(1)*1)*(i-1  )+  T.N_PwVar*(i    )+ T.S.CBW, ...
                                    T.S.FS2(2,1), ...
                                    T.S.CBW,        T.N_PhVar]);                     
    if strcmp(A.Fig2Var{i}.Title(1:3), 'STD')
        set(T.H.hFig2AxesVarColorbar(i),...
                'Ticks',        T.dAxesVarStdScaleTickLog,...
                'TickLabels',   T.dAxesVarStdScaleTickLabels);
    else
        set(T.H.hFig2AxesVarColorbar(i),...
                'Ticks',        0:0.2:1,...
                'TickLabels',   {'0%', '20%', '40%', '60%', '80%', '100%'});
    end
    T.H.hFig2AxesVarTitle(i) = title(A.Fig2Var{i}.Title,...
                'Tag',          ['TitlVar' num2str(i)],...
                'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
    xlabel( {[  'Max for all:    ',     sprintf('%5.2f%%', max(max(A.Fig2Var{i}.PhPw_Data))*100 ) ],...
             [  'Mean inside: ',        sprintf('%5.2f%%', sum(sum(A.Fig2Var{i}.PhPw_Data.*A.PhPw_ROIin))/sum(A.Pt_ROIin)*100 ) ],...
             [  'Min for all:     ',	sprintf('%5.2f%%', min(min(A.Fig2Var{i}.PhPw_Data))*100 ) ]},...          
                'Tag',          ['TitlVar' num2str(i)],...
                'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
    set(gca,    'LabelFontSizeMultiplier', 1);
end 

%% Axes: 1:1, Temp: Temporal traces for all IN pixels
% 'Average temporal response of a sound cycle';
T.H.hFig2AxesTemp = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(0  )+T.N_PwImg*(0  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg,	T.N_PhImg],...
            'Toolbar',      [],...
            'LabelFontSizeMultiplier', 1); 
plot(   (1:A.N_Fpt)*A.N_Tpf, A.FptPt_NormTrl(:,A.PtIndex_ROIin)   );
set(gca,    'XLim',         A.N_Tpf*            [0 A.N_Fpt],...
            'YLim',         T.dAxesTempYLim*    [-1 1]);    
if      A.N_Ftpreoff >0 && A.N_Ftstimoff<A.N_Fpt
    set(gca,'XTick',        A.N_Tpf*    [0 A.N_Ftpreoff A.N_Ftstimoff A.N_Fpt]); 
elseif	A.N_Ftpreoff >0 
    set(gca,'XTick',        A.N_Tpf*    [0 A.N_Ftpreoff A.N_Fpt]);
elseif	A.N_Ftstimoff<A.N_Fpt
    set(gca,'XTick',        A.N_Tpf*    [0 A.N_Ftstimoff A.N_Fpt]);  
else
    set(gca,'XTick',        A.N_Tpf*    [0 A.N_Fpt]);
end      
xlabel({['Trial time (s)'] },...
            'Parent',       gca,...
            'VerticalAlignment',    'middle');
ylabel({'Norm. signal, in raw polarity'},...
            'Parent',       gca,...
            'VerticalAlignment',    'Middle');
T.H.hFig2AxesTempTitle = title('Temporal, trace, average across reps',...
            'Tag',          'TitlTemp',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
set(gca,    'XGrid',        'on',... 
            'LabelFontSizeMultiplier', 1);
T.H.hFig2AxesTempHid = axes(...
            'Parent',       T.H.hFig2,... 
            'Units',        'pixels',...                        
            'Position',     get(T.H.hFig2AxesTemp, 'position'),...
            'Color',        'none',...
            'XLim',         [0 A.N_Fpt],...
            'YLim',         [0 1],...
            'XTick',        [],...
            'YTick',        [],...
            'Toolbar',      [],...
            'NextPlot',     'add');
text(   A.N_Fpt*0.04,	0.03, {'STD:'...
    sprintf('Max:  %5.2f%%',	100*A.PtIn_STD_max),...
    sprintf('Mean:%5.2f%%',     100*A.PtIn_STD_mean) },...
            'Parent',       T.H.hFig2AxesTempHid,...
            'FontSize',     T.FontSizeS,...
            'HorizontalAlignment',	'Left',...
            'VerticalAlignment',	'Bottom');
T.H.hFig2AxesTempTextNum =    text(   A.N_Fpt*0.04,	0.97, sprintf('@%4.1fs',0.2),...
            'Parent',       T.H.hFig2AxesTempHid,...
            'FontSize',     T.FontSizeS,...
            'HorizontalAlignment',	'Left');
T.H.hFig2AxesTempTextRight =  text(   A.N_Fpt*0.95,   0.9, '>',...
            'Parent',       T.H.hFig2AxesTempHid,...
            'FontSize',     T.FontSizeS,...
            'FontWeight',   'Bold',...
            'Tag',          'TempFrmeUp',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesTempTextLeft =   text(   A.N_Fpt*0.05,   0.9, '<',...
            'Parent',       T.H.hFig2AxesTempHid,...
            'FontSize',     T.FontSizeS,...
            'FontWeight',   'Bold',...
            'Tag',          'TempFrmeDown',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');            
T.H.hFig2AxesTempDot = plot(1, 1, 'o',...
            'Parent',       T.H.hFig2AxesTempHid,...
            'MarkerSize',   5,...
            'Color',        [1 0 0]);
%% Axes: 2:1, Pixl: Temporal traces for a selected pixel
T.H.hFig2AxesPixl = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(0  )+T.N_PwImg*(0  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(2  )+T.N_PhImg*(1  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg,	T.N_PhImg],...
            'Box',          'on',...
            'Toolbar',      [],...
            'NextPlot',     'add');  
T.H.hFig2AxesPixlLineAll = plot(   A.N_Tpf*   (1:A.N_Fpt),...
        squeeze( A.FptCtPhPw_NormTrl(:,:,A.N_PhSelect,A.N_PwSelect) ),...
            'Parent',       T.H.hFig2AxesPixl,...
            'LineWidth',    0.5);
for i = 1:A.N_Ct
	T.H.hFig2AxesPixlLineAll(i).Color = ...
        hsv2rgb( [ 0.8*(i-1)/A.N_Ct, 0.8*[1 1] ] );
end
T.H.hFig2AxesPixlLineMean = plot(   A.N_Tpf*  (1:A.N_Fpt),...
        mean(squeeze( A.FptCtPhPw_NormTrl(:,:,A.N_PhSelect,A.N_PwSelect) ),2),...
            'Parent',       T.H.hFig2AxesPixl,...
            'LineWidth',    2,...
            'Color',        [0 0 0]);   
xlabel({['Trial time (s)'] },...
            'Parent',       gca,...
            'VerticalAlignment',    'middle');
ylabel({'Norm. signal, in raw polarity'},...
            'Parent',       gca,...
            'VerticalAlignment',    'Middle');   
T.H.hFig2AxesPixlTitle = title(...
    sprintf('Pixel: (%dH,%dW) temporal traces on reps', A.N_PhSelect,A.N_PwSelect),...
            'Tag',          'TitlPixl',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
set(gca,    'XLim',         A.N_Tpf*    [0 A.N_Fpt]); 
set(gca,    'XTick',        get(T.H.hFig2AxesTemp,    'XTick'));
set(gca,    'XGrid',        'on',... 
            'LabelFontSizeMultiplier', 1);  
T.H.hFig2AxesPixlHid = axes(...
            'Parent',       T.H.hFig2,... 
            'Units',        'pixels',...                        
            'Position',     get(T.H.hFig2AxesPixl, 'position'),...
            'Color',        'none',...
            'XLim',         [0 A.N_Fpt],...
            'YLim',         [0 1],...
            'XTick',        [],...
            'YTick',        [],...
            'Toolbar',      [],...
            'NextPlot',     'add');
T.H.hFig2AxesPixlText = text(   A.N_Fpt*0.04,	0.97, {...
    sprintf('Across-all:      %5.2f%%', 100*std(reshape(A.FptCtPhPw_NormTrl(:,:,A.N_PhSelect,A.N_PwSelect), 1, []))),...
    sprintf('Across-rep:    %5.2f%%',	100*std(mean(A.FptCtPhPw_NormTrl(:,:,A.N_PhSelect,A.N_PwSelect), 2), 0, 1)),...
    sprintf('Across-frame:%5.2f%%',     100*std(mean(A.FptCtPhPw_NormTrl(:,:,A.N_PhSelect,A.N_PwSelect), 1), 0, 2)),...
    'on STD'},...
            'Parent',       T.H.hFig2AxesPixlHid,...
            'FontSize',     T.FontSizeS,...
            'HorizontalAlignment',	'Left',...
            'VerticalAlignment',	'Cap');

%% Axes 1:2, Spectrum
T.H.hFig2AxesSpec = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...                      
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(1  )+T.N_PwImg*(1  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg       T.N_PhImg],...
            'Box',          'on',...
            'Toolbar',      [],...
            'NextPlot',     'add');
    plot(A.Qt_Freqs, A.OneQt_FFTAmpMeanIn);
    plot(A.Qt_Freqs, A.OneQt_FFTAmpMeanOut);
    plot(A.Qt_Freqs, A.OneQt_FFTAmpMeanPStdIn, 'b:');
T.H.hFig2AxesSpecLinePixlSelect = ...
    plot(A.Qt_Freqs, A.PtQt_FFTAmp(A.N_PhSelect + A.N_PwSelect*A.N_Ph,:));
    plot(A.Qt_Freqs, A.OneQt_PowerFFTAmp);
T.H.hFig2AxesSpecDot = plot(T.dAxesSpecDotX, T.dAxesSpecDotY, 'o',...
            'MarkerSize',   5,...
            'Color',        [1 0 0]);
set(gca,    'XTick',        T.dAxesSpecXTick,... 
            'XLim',         [A.Qt_Freqs(2)  mean(A.Qt_Freqs([2, end]))],...
            'YLim',         [0              T.dAxesSpecDotY],...
            'YTick',        T.dAxesSpecYTick,...
            'YTickLabel',   T.dAxesSpecYTickLabel,...
            'XGrid',        'on',...
            'XScale',       'log',...
            'LabelFontSizeMultiplier', 1);
                            xlabel({['Frequency (Hz)']},...
            'Parent',       gca,...
            'VerticalAlignment',    'middle');
T.H.hFig2AxesSpecYLabel =	ylabel({['Amplitude']},...
            'Parent',       gca,...
            'VerticalAlignment',    'Bottom',...
            'Tag',          'AmpSpectrum',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesSpecTitle = title('Spectrum, signal of selected pixel or pixels',...
            'Tag',          'TitlSpec',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
legend(     {'In ROI mean', 'Out ROI mean', 'In ROI mean+std', 'Selected pixel', 'Power meter'},...
            'Location',     'Northeast',...
            'FontSize',     T.FontSizeS);
legend('boxoff'); 
T.H.hFig2AxesSpecHid = axes(...
            'Parent',       T.H.hFig2,... 
            'Units',        'pixels',...                        
            'Position',     get(T.H.hFig2AxesSpec, 'position'),...
            'Color',        'none',...
            'Toolbar',      [],...
            'XLim',         [0 1],...
            'YLim',         [0 1],...
            'XTick',        [],...
            'YTick',        []);
T.H.hFig2AxesSpecTextNum =    text(   0.98,    0.97, sprintf('Rep#:%d',A.N_Ct),...
            'Parent',       T.H.hFig2AxesSpecHid,...
            'FontSize',     T.FontSizeS,...
            'HorizontalAlignment',	'right');
T.H.hFig2AxesSpecTextRight =  text(   0.95,   0.9, '>',...
            'Parent',       T.H.hFig2AxesSpecHid,...
            'FontSize',     T.FontSizeS,...
            'FontWeight',   'Bold',...
            'Tag',          'SpecNumUp',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesSpecTextLeft =   text(   0.05,   0.9, '<',...
            'Parent',       T.H.hFig2AxesSpecHid,...
            'FontSize',     T.FontSizeS,...
            'FontWeight',   'Bold',...
            'Tag',          'SpecNumDown',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
        
%% Axes: 2:2, Frme: Frame at a given time point        
T.H.hFig2AxesFrme = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(1  )+T.N_PwImg*(1  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(2  )+T.N_PhImg*(1  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg,	T.N_PhImg],...
            'Toolbar',      [],...
            'LabelFontSizeMultiplier', 1);  
T.H.hFig2AxesFrmeImage = imagesc(squeeze(A.FptPhPw_NormTrlAdj(1,:,:)),...
            'Parent',       T.H.hFig2AxesFrme,...
            'Tag',          'PixlSelectionFromFrmeImage',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesFrmeXLabel = xlabel(...
    sprintf('Amplitude @ %4.1f s, in adjusted polarity, click to play', 1*A.N_Tpf),...
            'Parent',       gca,...
            'VerticalAlignment',    'Top', ...
            'Tag',          'Playback',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesFrmeTitle = title('Frame, at a given time point',...
            'Tag',          'TitlFrme',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
set(T.H.hFig2AxesFrme,'XTick',        []);
set(T.H.hFig2AxesFrme,'YTick',        []);            
colormap(   T.H.hFig2AxesFrme, 'jet');
T.H.hFig2AxesFrmeScalebar = colorbar(...
            'peer',         T.H.hFig2AxesFrme,...
            'Units',        'pixels',...
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(1  )+T.N_PwImg*(1  )-2*T.S.CBW, ...
                                T.S.FS2(2,1)+T.S.BA(2)*(2  )+T.N_PhImg*(1  )+T.N_PhVar*(1  ), ...
                                T.S.CBW,            T.N_PhImg],...   
            'Limits',       0.05*[-1 1],...
            'Tag',          'FrmeScalebar',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
set(gca,    'LabelFontSizeMultiplier', 1);

%% Axes: 1:3 Phase, tuning map
T.H.hFig2AxesTune = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...                      
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(2  )+T.N_PwImg*(2  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg       T.N_PhImg],...
            'Toolbar',      [],...
            'NextPlot',     'add',...
            'LabelFontSizeMultiplier', 1);   
T.H.hFig2AxesTuneTitle = title('Phase, tuning map',...
            'Tag',          'TitlTune',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
T.H.hFig2AxesTuneImage = image(T.H.hFig2AxesTune, A.PhPwThree_TuneMap,...
            'Tag',          'PixlSelectionFromTuneImage',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
set(T.H.hFig2AxesTune, ...
            'YDir',         'reverse',...
            'XLim',         [1 A.N_Pw],...
            'YLim',         [1 A.N_Ph],...
            'XTick',        [],...
            'YTick',        []);
T.H.hFig2AxesTuneXLabel = xlabel(...
    sprintf('Hue: %3.1f s compensated phase angle; Value: phase amplitude', A.PseudoDelay),...
            'Tag',          'TitlTuIm',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
% Scalebar: Hue
T.H.hFig2AxesTuneHidHue = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     get(T.H.hFig2AxesTune, 'position'),...
            'Visible',     'off'); 
colormap(   T.H.hFig2AxesTuneHidHue, 'hsv');                     caxis( [0 1]);
T.H.hFig2SpecScalebarHue = colorbar(...
            'peer',         T.H.hFig2AxesTuneHidHue,...
            'Units',        'pixels',...
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(2  )+T.N_PwImg*(3  )+T.S.CBW*(1 )+T.S.CBTW*(0 ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.S.CBW             T.N_PhImg],...
            'Ticks',        [],...
            'Tag',          'TuneScalebarHue',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
% Scalebar: Saturation
T.H.hFig2AxesTuneHidSat = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     get(T.H.hFig2AxesTune, 'position'),...
            'Visible',      'off'); 
colormap(   T.H.hFig2AxesTuneHidSat,...
        hsv2rgb([1/3*ones(64,1) (0:1/63:1)' 0.5*ones(64,1)]) );	caxis( [0 1]);
T.H.hFig2SpecScalebarSat = colorbar(...
            'peer',         T.H.hFig2AxesTuneHidSat,...
            'Units',        'pixels',...
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(2  )+T.N_PwImg*(3  )+T.S.CBW*(2 )+T.S.CBTW*(1 ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.S.CBW             T.N_PhImg],...
            'Ticks',        [],...
            'Tag',          'TuneScalebarSat',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown'); 
% Scalebar: Value
T.H.hFig2AxesTuneHidVal = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...  
            'Position',     get(T.H.hFig2AxesTune, 'position'),...
            'Visible',      'off'); 
colormap(   T.H.hFig2AxesTuneHidVal,  'gray');     caxis( [0 1]);
T.H.hFig2SpecScalebarVal = colorbar(...
            'peer',         T.H.hFig2AxesTuneHidVal,...
            'Units',        'pixels',...
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(2  )+T.N_PwImg*(3  )+T.S.CBW*(3 )+T.S.CBTW*(2 ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(1  )+T.N_PhImg*(0  )+T.N_PhVar*(1  ), ...
                                T.S.CBW             T.N_PhImg],...
            'Ticks',        [],...
            'Tag',          'TuneScalebarVal',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
        
%% Axes: 2:3, Phase Histogram
T.H.hFig2AxesHist = axes(...
            'Parent',       T.H.hFig2,...
            'Units',        'pixels',...      
            'Position',     [   T.S.FS2(1,1)+T.S.BA(1)*(2  )+T.N_PwImg*(2  ), ...
                                T.S.FS2(2,1)+T.S.BA(2)*(2  )+T.N_PhImg*(1  )+T.N_PhVar*(1  ), ...
                                T.N_PwImg       T.N_PhImg],...
            'Box',          'on',...
            'Toolbar',      [],...
            'NextPlot',     'add',...
            'LabelFontSizeMultiplier', 1); 
T.H.hFig2AxesHistHistogramAll =   histogram(...
	squeeze(A.PtQt_FFTAgl(:,A.N_Qfc)), pi*(0:1/16:2),...
            'Parent',       T.H.hFig2AxesHist);
T.H.hFig2AxesHistHistogramIn =    histogram(...
    squeeze(A.PtQt_FFTAgl(A.PtIndex_ROIin,21)), pi*(0:1/16:2),...
            'Parent',       T.H.hFig2AxesHist);
set(T.H.hFig2AxesHist,...
            'XLim',         [0 2*pi],...
            'XTick',        (0:0.25:2)*pi,...
            'XTickLabels',  {   '0.00\pi', '0.25\pi', '0.50\pi', '0.75\pi',...
                                '1.00\pi', '1.25\pi', '1.50\pi', '1.75\pi',...
                                '2.00\pi'},...
            'XTickLabelRotation',   30);
xlabel(sprintf('Phase, %3.1f s compensated', A.PseudoDelay));
ylabel('Pixel count');
T.H.hFig2AxesHistTitle = title('Phase, histogram among pixels',...
            'Tag',          'TitlHist',...
            'ButtonDownFcn','XinRanAnalysis2_Sweep_ButtonDown');
legend(     {'All pixels', 'In ROI'},...
            'Location',     'Northwest',...
            'FontSize',     T.FontSizeS,...
            'Box',          'off');

%% Setup Data
setappdata(T.H.hFig2,   'hAxesVar1',        T.H.hFig2AxesVar(1));
setappdata(T.H.hFig2,   'hAxesVar2',        T.H.hFig2AxesVar(2));
setappdata(T.H.hFig2,   'hAxesVar3',        T.H.hFig2AxesVar(3));
setappdata(T.H.hFig2,   'hAxesTemp',        T.H.hFig2AxesTemp);
setappdata(T.H.hFig2,   'hAxesPixl',        T.H.hFig2AxesPixl);
setappdata(T.H.hFig2,   'hAxesSpec',        T.H.hFig2AxesSpec);
setappdata(T.H.hFig2,   'hAxesFrme',        T.H.hFig2AxesFrme);
setappdata(T.H.hFig2,   'hAxesTune',        T.H.hFig2AxesTune);
setappdata(T.H.hFig2,	'hAxesTuneHueHid',	T.H.hFig2AxesTuneHidHue); 
setappdata(T.H.hFig2,   'hAxesHist',        T.H.hFig2AxesHist);

setappdata(T.H.hFig2,   'hImageTune',   T.H.hFig2AxesTuneImage);
setappdata(T.H.hFig2,   'hImageFrme',   T.H.hFig2AxesFrmeImage);

setappdata(T.H.hFig2,   'hHistAll',	T.H.hFig2AxesHistHistogramAll);
setappdata(T.H.hFig2,   'hHistIn',	T.H.hFig2AxesHistHistogramIn);

setappdata(T.H.hFig2,	'hLinePixlAll',     T.H.hFig2AxesPixlLineAll);
setappdata(T.H.hFig2,	'hLinePixlMean',	T.H.hFig2AxesPixlLineMean);
setappdata(T.H.hFig2,   'hLineSpecPixl',    T.H.hFig2AxesSpecLinePixlSelect);

setappdata(T.H.hFig2,   'hDotTemp',     T.H.hFig2AxesTempDot);
setappdata(T.H.hFig2,   'hDotSpec',     T.H.hFig2AxesSpecDot);

setappdata(T.H.hFig2,   'hTextTemp',        T.H.hFig2AxesTempTextNum);
setappdata(T.H.hFig2,   'hTextTempRight',	T.H.hFig2AxesTempTextRight);
setappdata(T.H.hFig2,   'hTextPixl',        T.H.hFig2AxesPixlText);
setappdata(T.H.hFig2,   'hTextPixl',        T.H.hFig2AxesPixlText);
setappdata(T.H.hFig2,	'hTextSpecRepNum',	T.H.hFig2AxesSpecTextNum);
setappdata(T.H.hFig2,	'hTextFrmeXLabel',	T.H.hFig2AxesFrmeXLabel);     

setappdata(T.H.hFig2,   'dFrmeTime',            A.N_Tpf);
setappdata(T.H.hFig2,	'dTrlDurPreStim',       A.N_Ttps);
setappdata(T.H.hFig2,	'dTrlDurStim',          A.N_Tts);
setappdata(T.H.hFig2,   'dTrlDurTotal',         A.N_Ttt);
setappdata(T.H.hFig2,   'dSesDurTotal',         A.N_Tst);
setappdata(T.H.hFig2,   'dQCycNum',             A.N_Qfc);
setappdata(T.H.hFig2,   'dAxesTempYLims',       T.dAxesTempYLims); 
setappdata(T.H.hFig2,   'dSoundWave',           A.SoundWave);
setappdata(T.H.hFig2,   'dFptCtPhPw_NormTrl',   A.FptCtPhPw_NormTrl);
setappdata(T.H.hFig2,	'dFptPhPw_NormTrlAdj',	A.FptPhPw_NormTrlAdj);
setappdata(T.H.hFig2,	'dPtQt_FFTAmp',         A.PtQt_FFTAmp);
setappdata(T.H.hFig2,   'dPtQt_FFTAgl',         A.PtQt_FFTAgl);
setappdata(T.H.hFig2,   'dPtIndex_ROIin',       A.PtIndex_ROIin);
setappdata(T.H.hFig2,	'dRawHue',              A.PtOne_Hue);
setappdata(T.H.hFig2,	'dRawSat',              A.PtOne_Sat);
setappdata(T.H.hFig2,	'dRawVal',              A.PtOne_Val);

setappdata(T.H.hFig2,   'cFrmeNum',     1);
setappdata(T.H.hFig2,   'cPlayingNow',  0); 
setappdata(T.H.hFig2,	'cQRepNum',     A.N_Qfc);
% setappdata(T.H.hFig2,   '', );

% Axes: Tune 
setappdata(T.H.hFig2AxesTuneImage,	'HueMapOptions', {  'HSLuvCircular','HSLuvLinear'});        % 'HSLuvZigZag'
setappdata(T.H.hFig2AxesTuneImage,	'HueMapOrder',      1);
setappdata(T.H.hFig2AxesTuneImage,	'HueMap',           'HSLuvCircular');
setappdata(T.H.hFig2AxesTuneImage,	'HueTempolate',     []);
setappdata(T.H.hFig2AxesTuneImage,	'HueColorMap',      []);   
setappdata(T.H.hFig2AxesTuneImage,	'SatParaRange',	[   0   0   0           0   1   1   1;
                                                        1   1   1           0   0   1   1;
                                                        0   0.6 -A.N_Tts/2  0   0   0.6 0]);
setappdata(T.H.hFig2AxesTuneImage,	'SatParaOrder',     2);
setappdata(T.H.hFig2AxesTuneImage,	'SatValSync',       0);
setappdata(T.H.hFig2AxesTuneImage,	'SatGroundOut',     1);
setappdata(T.H.hFig2AxesTuneImage,	'SatGroundTime',	0);
setappdata(T.H.hFig2AxesTuneImage,	'ValLimRange',      0.025/100*2.^(0:0.5:7));
setappdata(T.H.hFig2AxesTuneImage,	'ValLimOrder',      5); 
setappdata(T.H.hFig2AxesTuneImage,	'ValLim',           0.1/100);   
        
% Axes: Temp
setappdata(T.H.hFig2AxesSpecTextRight,'UpDown',           +1);
setappdata(T.H.hFig2AxesSpecTextLeft, 'UpDown',           -1);
setappdata(T.H.hFig2AxesTempTextRight,'UpDown',           +1);
setappdata(T.H.hFig2AxesTempTextLeft, 'UpDown',           -1);

% Updates
% drawnow;                                  
XinRanAnalysis2_Sweep_ButtonDown(T.H.hFig2SpecScalebarHue);         
XinRanAnalysis2_Sweep_ButtonDown(T.H.hFig2SpecScalebarSat);       
XinRanAnalysis2_Sweep_ButtonDown(T.H.hFig2SpecScalebarVal); 
XinRanAnalysis2_Sweep_ButtonDown(T.H.hFig2AxesFrmeScalebar);  

drawnow;

%% Save
% remember to set Preference -> General -> Mat-files to be
% "MATLAB Version 7.3 or later (save -7.3)" to save data > 2GB, even for
% saving figure through savefig, it applies.
A.FileNameMod = [A.FileNameMod sprintf('_%3.1fs', A.PseudoDelay)];
savefig(T.H.hFig2, [A.PathName,A.FileName{1}(1:end-7), A.FileNameMod, '_Sweep.fig'], 'compact'); 
T.H.hFig2.Name = [T.H.hFig2.Name 'SAVED'];
